spring.datasource.url=jdbc:mysql://localhost:3307/foldr?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=foldr_user
spring.datasource.password=foldr_pass

spring.jpa.show-sql=true